# 1. Files excluded from Jekyll builds
exclude:
- README.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- screenshot.png
- LICENSE
- CNAME
- Gemfile
- Gemfile.lock
- alembic-jekyll-theme.gemspec
- .jekyll-cache

# 2. Installed Gems
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jemoji

# 4. Jekyll settings
sass:
  style: compressed # Style compression
permalink: pretty  # Permalink style (/YYYY/MM/DD/page-name/)

# 6. Jekyll collections settings
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page # Set the default layout for pages

# 7. Site settings
encoding: utf-8 # Make sure the encoding is right
lang: en-GB # Set the site language
title: "quantUM group" # Site name or title, also used in jekyll-seo-tag
#logo: "/assets/logos/logo.svg" # Site logo, also used in jekyll-seo-tag
description: "Quantum group of the University of Minho" # Site description and default description, also used in jekyll-seo-tag
url: "https://vegf17.github.io/" # Site url, also used in jekyll-seo-tag
baseurl: ""
#css_inline: true # Will insert all styles into a single <style> block in the <head> element and remove the style <link> reference

# 9. Site navigation
navigation_header:
- title: Home
  url: /
- title: News
  url: /news/
- title: Members
  url: /members/
- title: Seminars
  url: /seminars/
#- title: Search
#  url: /search/
#- title: Fork Alembic
#  url: https://github.com/daviddarnes/alembic
#- title: 404
#  url: /404/

navigation_footer:
- title: Back to top
  url: "#top"
#- title: Template created by David Darnes
#  url: https://darn.es

# Load custom fonts from fonts.google.com etc
#
# TIP: Try to keep the number of urls as low to reduce the performance cost
#      If multiple fonts can be requested in a single url opt for this
fonts:
  preconnect_urls:
    - https://fonts.gstatic.com
  font_urls:
    - https://fonts.googleapis.com/css2?family=Merriweather:wght@400;700&display=swap
